site_name: MkDocs static i18n plugin demo
site_url: https://ultrabug.github.io/mkdocs-static-i18n
repo_url: https://github.com/ultrabug/mkdocs-static-i18n

theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/file-document-multiple
  palette:
    primary: blue

extra:
  alternate:
    - name: Default (en)
      link: ./
      lang: en
    - name: English
      link: ./en/
      lang: en
    - name: Français
      link: ./fr/
      lang: fr
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ultrabug/mkdocs-static-i18n
      name: mkdocs-static-i18n on Github

markdown_extensions:
  - admonition

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: english
        fr: français
